Added c++ lib, changed structure and updated ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,14 +25,60 @@ jobs:
       with:
         python-version: "3.12"
 
+    # Cache Python dependencies
+    - name: Cache Python dependencies
+      uses: actions/cache@v3
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-python-
+
     # Install dependencies (update this based on your project's requirements)
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt  # Assumes your project has a requirements.txt
+        sudo apt-get update
+        sudo apt-get install -y g++ cmake libomp-dev
+        python3 -m pip install --upgrade pip
+        python3 -m pip install -r requirements.txt
+
+    # Cache and install Eigen
+    - name: Cache Eigen
+      uses: actions/cache@v3
+      with:
+        path: eigen/
+        key: eigen-cache-v1
+        restore-keys: |
+          eigen-cache-
+
+    - name: Install Eigen
+      run: |
+        if [ ! -d "eigen" ]; then
+          mkdir -p eigen
+          curl -L https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz | tar xz --strip-components=1 -C eigen
+        fi
+
+    # Configure the C++ project using CMake
+    - name: Configure the C++ project
+      run: |
+        mkdir -p build
+        cd build
+        cmake ..
+
+    # Build the C++ extension using CMake
+    - name: Build the C++ extension
+      run: |
+        cd build
+        make
+    # Step 4: Build the C++ extension
+    #- name: Build C++ extension
+    #  run: |
+    #    set -e  # Fail fast on errors
+    #    c++ -O3 -Wall -shared -std=c++17 -fPIC -fopenmp -march=native \
+    #    -I ./eigen `python3 -m pybind11 --includes` src/cpp/displacement_calc.cpp \
+    #    -o src/python/georeferencer/libdiscalc`python3-config --extension-suffix`
 
     # Run pytest on the tests directory
     - name: Run tests with pytest
       run: |
-        pip install pytest  # Install pytest if not in requirements
-        pytest ./tests
+        python3 -m pytest ./tests
